POST http://localhost:4000/libros/create/nosql
Content-Type: application/json

{
  "isbn": "12345678901",
  "titulo": "El libro de prueba1",
  "autor": "Autor de prueba1",
  "categoria": "Ficción1",
  "descripción": "1Una breve descripción del libro de prueba.",
  "imagen": ["imagen1.jpg", "imagen2.jpg"]
}


